/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes': RouteRecordInfo<
      '/notes',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/photos': RouteRecordInfo<
      '/photos',
      '/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blender-弯曲修改器做器皿_详解': RouteRecordInfo<
      '/posts/blender-弯曲修改器做器皿_详解',
      '/posts/blender-%E5%BC%AF%E6%9B%B2%E4%BF%AE%E6%94%B9%E5%99%A8%E5%81%9A%E5%99%A8%E7%9A%BF_%E8%AF%A6%E8%A7%A3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/clean-github-action-zh': RouteRecordInfo<
      '/posts/clean-github-action-zh',
      '/posts/clean-github-action-zh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-surge-again-zh': RouteRecordInfo<
      '/posts/hello-surge-again-zh',
      '/posts/hello-surge-again-zh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-vitesse': RouteRecordInfo<
      '/posts/hello-vitesse',
      '/posts/hello-vitesse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    'pages/notes.md': {
      routes:
        | '/notes'
      views:
        | never
    }
    'pages/photos.md': {
      routes:
        | '/photos'
      views:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/blender-弯曲修改器做器皿_详解.md': {
      routes:
        | '/posts/blender-弯曲修改器做器皿_详解'
      views:
        | never
    }
    'pages/posts/clean-github-action-zh.md': {
      routes:
        | '/posts/clean-github-action-zh'
      views:
        | never
    }
    'pages/posts/hello-surge-again-zh.md': {
      routes:
        | '/posts/hello-surge-again-zh'
      views:
        | never
    }
    'pages/posts/hello-vitesse.md': {
      routes:
        | '/posts/hello-vitesse'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
